/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherMessagesRouteImport } from './routes/teacher.messages'
import { Route as TeacherHomeworkRouteImport } from './routes/teacher.homework'
import { Route as StudentTestRouteImport } from './routes/student.test'
import { Route as StudentSpeakingRouteImport } from './routes/student.speaking'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentPragmaticRouteImport } from './routes/student.pragmatic'
import { Route as StudentLessonsRouteImport } from './routes/student.lessons'
import { Route as StudentHomeworkRouteImport } from './routes/student.homework'
import { Route as StudentExercisesRouteImport } from './routes/student.exercises'
import { Route as StudentCertificatesRouteImport } from './routes/student.certificates'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as StudentLessonsIdRouteImport } from './routes/student.lessons.$id'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherHomeworkRoute = TeacherHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentTestRoute = StudentTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSpeakingRoute = StudentSpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPragmaticRoute = StudentPragmaticRouteImport.update({
  id: '/pragmatic',
  path: '/pragmatic',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLessonsRoute = StudentLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHomeworkRoute = StudentHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExercisesRoute = StudentExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const StudentLessonsIdRoute = StudentLessonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentLessonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/courses': typeof AdminCoursesRoute
'/student/progress': typeof StudentProgressRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/exercises': typeof StudentExercisesRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/lessons': typeof StudentLessonsRouteWithChildren
  '/student/pragmatic': typeof StudentPragmaticRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/speaking': typeof StudentSpeakingRoute
  '/student/test': typeof StudentTestRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/lessons/$id': typeof StudentLessonsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
'/student/progress': typeof StudentProgressRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/exercises': typeof StudentExercisesRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/lessons': typeof StudentLessonsRouteWithChildren
  '/student/pragmatic': typeof StudentPragmaticRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/speaking': typeof StudentSpeakingRoute
  '/student/test': typeof StudentTestRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/lessons/$id': typeof StudentLessonsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/exercises': typeof StudentExercisesRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/lessons': typeof StudentLessonsRouteWithChildren
  '/student/pragmatic': typeof StudentPragmaticRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/speaking': typeof StudentSpeakingRoute
  '/student/test': typeof StudentTestRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/lessons/$id': typeof StudentLessonsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/courses'
    | '/admin/settings'
    | '/admin/users'
    | '/student/certificates'
    | '/student/exercises'
    | '/student/homework'
    | '/student/lessons'
    | '/student/pragmatic'
    | '/student/profile'
    | '/student/speaking'
    | '/student/test'
    | '/teacher/homework'
    | '/teacher/messages'
    | '/teacher/students'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/lessons/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/courses'
    | '/admin/settings'
    | '/admin/users'
    | '/student/certificates'
    | '/student/exercises'
    | '/student/homework'
    | '/student/lessons'
    | '/student/pragmatic'
    | '/student/profile'
    | '/student/speaking'
    | '/student/test'
    | '/teacher/homework'
    | '/teacher/messages'
    | '/teacher/students'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/student/lessons/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/courses'
    | '/admin/settings'
    | '/admin/users'
    | '/student/certificates'
    | '/student/exercises'
    | '/student/homework'
    | '/student/lessons'
    | '/student/pragmatic'
    | '/student/profile'
    | '/student/speaking'
    | '/student/test'
    | '/teacher/homework'
    | '/teacher/messages'
    | '/teacher/students'
    | '/admin/'
    | '/student/'
    | '/teacher/'
    | '/student/lessons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/homework': {
      id: '/teacher/homework'
      path: '/homework'
      fullPath: '/teacher/homework'
      preLoaderRoute: typeof TeacherHomeworkRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/test': {
      id: '/student/test'
      path: '/test'
      fullPath: '/student/test'
      preLoaderRoute: typeof StudentTestRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/speaking': {
      id: '/student/speaking'
      path: '/speaking'
      fullPath: '/student/speaking'
      preLoaderRoute: typeof StudentSpeakingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/pragmatic': {
      id: '/student/pragmatic'
      path: '/pragmatic'
      fullPath: '/student/pragmatic'
      preLoaderRoute: typeof StudentPragmaticRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lessons': {
      id: '/student/lessons'
      path: '/lessons'
      fullPath: '/student/lessons'
      preLoaderRoute: typeof StudentLessonsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/homework': {
      id: '/student/homework'
      path: '/homework'
      fullPath: '/student/homework'
      preLoaderRoute: typeof StudentHomeworkRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exercises': {
      id: '/student/exercises'
      path: '/exercises'
      fullPath: '/student/exercises'
      preLoaderRoute: typeof StudentExercisesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/lessons/$id': {
      id: '/student/lessons/$id'
      path: '/$id'
      fullPath: '/student/lessons/$id'
      preLoaderRoute: typeof StudentLessonsIdRouteImport
      parentRoute: typeof StudentLessonsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentLessonsRouteChildren {
  StudentLessonsIdRoute: typeof StudentLessonsIdRoute
}

const StudentLessonsRouteChildren: StudentLessonsRouteChildren = {
  StudentLessonsIdRoute: StudentLessonsIdRoute,
}

const StudentLessonsRouteWithChildren = StudentLessonsRoute._addFileChildren(
  StudentLessonsRouteChildren,
)

interface StudentRouteChildren {
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentExercisesRoute: typeof StudentExercisesRoute
  StudentHomeworkRoute: typeof StudentHomeworkRoute
  StudentLessonsRoute: typeof StudentLessonsRouteWithChildren
  StudentPragmaticRoute: typeof StudentPragmaticRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSpeakingRoute: typeof StudentSpeakingRoute
  StudentTestRoute: typeof StudentTestRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentProgressRoute: typeof StudentProgressRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentExercisesRoute: StudentExercisesRoute,
  StudentHomeworkRoute: StudentHomeworkRoute,
  StudentLessonsRoute: StudentLessonsRouteWithChildren,
  StudentPragmaticRoute: StudentPragmaticRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSpeakingRoute: StudentSpeakingRoute,
  StudentTestRoute: StudentTestRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentProgressRoute: StudentProgressRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherHomeworkRoute: typeof TeacherHomeworkRoute
  TeacherMessagesRoute: typeof TeacherMessagesRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherHomeworkRoute: TeacherHomeworkRoute,
  TeacherMessagesRoute: TeacherMessagesRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
